service: nuxt-product-pages 
package:
  individually: true
  # exclude:
    # - ./**
    # - '!node_modules/**'


functions:
  nuxt:
    package:
      exclude:
        - client/**
      # include:
        # - .nuxt/**
        # - server/**
    handler: server/serverless.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-central-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-offline


custom:
  secrets: ${file(server/secrets.json)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ''
    stage: ${self:custom.secrets.NODE_ENV}
    createRoute53Record: true