/* eslint-disable */
import './arrow'
import './attention'
import './back'
import './cart'
import './checkmark'
import './chevron-up'
import './chevron'
import './close'
import './gift'
import './info'
import './more'
import './play'
